// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace EFPOCOGen
{

    // Course
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.2.0")]
    public partial class Course
    {
        public int CourseId { get; set; } // CourseID (Primary key)
        public string Title { get; set; } // Title (length: 50)
        public int? Credits { get; set; } // Credits
        public int DepartmentId { get; set; } // DepartmentID
        public System.DateTime CreatedOn { get; set; } // CreatedOn
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public int CourseType { get; set; } // CourseType

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Enrollment> Enrollments { get; set; } // Enrollment.FK_dbo.Enrollment_dbo.Course_CourseID
        public virtual System.Collections.Generic.ICollection<Person> People { get; set; } // Many to many mapping

        // Foreign keys
        public virtual Department Department { get; set; } // FK_dbo.Course_dbo.Department_DepartmentID
        
        public Course()
        {
            DepartmentId = 1;
            CreatedOn = System.DateTime.Now;
            CourseType = 0;
            Enrollments = new System.Collections.Generic.List<Enrollment>();
            People = new System.Collections.Generic.List<Person>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
