// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace EFPOCOGen
{

    // Department
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.2.0")]
    public partial class Department
    {
        public int DepartmentId { get; set; } // DepartmentID (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public decimal Budget { get; set; } // Budget
        public System.DateTime StartDate { get; set; } // StartDate
        public int? InstructorId { get; set; } // InstructorID
        public byte[] RowVersion { get; set; } // RowVersion (length: 8)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Course> Courses { get; set; } // Course.FK_dbo.Course_dbo.Department_DepartmentID

        // Foreign keys
        public virtual Person Person { get; set; } // FK_dbo.Department_dbo.Instructor_InstructorID
        
        public Department()
        {
            Courses = new System.Collections.Generic.List<Course>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
