// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace EFPOCOGen
{

    public interface IContosoUniversityEntities : System.IDisposable
    {
        System.Data.Entity.DbSet<Course> Courses { get; set; } // Course
        System.Data.Entity.DbSet<Department> Departments { get; set; } // Department
        System.Data.Entity.DbSet<Enrollment> Enrollments { get; set; } // Enrollment
        System.Data.Entity.DbSet<OfficeAssignment> OfficeAssignments { get; set; } // OfficeAssignment
        System.Data.Entity.DbSet<Person> People { get; set; } // Person
        System.Data.Entity.DbSet<Sysdiagram> Sysdiagrams { get; set; } // sysdiagrams
        System.Data.Entity.DbSet<VwDept> VwDepts { get; set; } // vwDept
        System.Data.Entity.DbSet<VwDeptCourseCount> VwDeptCourseCounts { get; set; } // vwDeptCourseCount

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        
        // Stored Procedures
        int DepartmentDelete(int? departmentId, byte[] rowVersionOriginal);
        System.Collections.Generic.List<DepartmentInsertReturnModel> DepartmentInsert(string name, decimal? budget, System.DateTime? startDate, int? instructorId);
        System.Collections.Generic.List<DepartmentInsertReturnModel> DepartmentInsert(string name, decimal? budget, System.DateTime? startDate, int? instructorId, out int procResult);
        System.Collections.Generic.List<DepartmentUpdateReturnModel> DepartmentUpdate(int? departmentId, string name, decimal? budget, System.DateTime? startDate, int? instructorId, byte[] rowVersionOriginal);
        System.Collections.Generic.List<DepartmentUpdateReturnModel> DepartmentUpdate(int? departmentId, string name, decimal? budget, System.DateTime? startDate, int? instructorId, byte[] rowVersionOriginal, out int procResult);
        System.Collections.Generic.List<GetDeptReturnModel> GetDept(int? id);
        System.Collections.Generic.List<GetDeptReturnModel> GetDept(int? id, out int procResult);
        int InsertDept(string name, decimal? budget);
    }

}
// </auto-generated>
