// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace EFPOCOGen
{

    // OfficeAssignment
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.2.0")]
    public partial class OfficeAssignmentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OfficeAssignment>
    {
        public OfficeAssignmentConfiguration()
            : this("dbo")
        {
        }
 
        public OfficeAssignmentConfiguration(string schema)
        {
            ToTable(schema + ".OfficeAssignment");
            HasKey(x => x.InstructorId);

            Property(x => x.InstructorId).HasColumnName(@"InstructorID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Location).HasColumnName(@"Location").IsOptional().HasColumnType("nvarchar").HasMaxLength(50);

            // Foreign keys
            HasRequired(a => a.Person).WithOptional(b => b.OfficeAssignment); // FK_dbo.OfficeAssignment_dbo.Instructor_InstructorID
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
