// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace EFPOCOGen
{

    // Person
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.2.0")]
    public partial class Person
    {
        public int Id { get; set; } // ID (Primary key)
        public string LastName { get; set; } // LastName (length: 50)
        public string FirstName { get; set; } // FirstName (length: 50)
        public System.DateTime? HireDate { get; set; } // HireDate
        public System.DateTime? EnrollmentDate { get; set; } // EnrollmentDate
        public string Discriminator { get; set; } // Discriminator (length: 128)

        // Reverse navigation
        public virtual OfficeAssignment OfficeAssignment { get; set; } // OfficeAssignment.FK_dbo.OfficeAssignment_dbo.Instructor_InstructorID
        public virtual System.Collections.Generic.ICollection<Course> Courses { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<Department> Departments { get; set; } // Department.FK_dbo.Department_dbo.Instructor_InstructorID
        public virtual System.Collections.Generic.ICollection<Enrollment> Enrollments { get; set; } // Enrollment.FK_dbo.Enrollment_dbo.Person_StudentID
        
        public Person()
        {
            Discriminator = "Instructor";
            Departments = new System.Collections.Generic.List<Department>();
            Enrollments = new System.Collections.Generic.List<Enrollment>();
            Courses = new System.Collections.Generic.List<Course>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
