// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace EFPOCOGen
{

    // vwDept
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.2.0")]
    public partial class VwDeptConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<VwDept>
    {
        public VwDeptConfiguration()
            : this("dbo")
        {
        }
 
        public VwDeptConfiguration(string schema)
        {
            ToTable(schema + ".vwDept");
            HasKey(x => x.DeptName);

            Property(x => x.DeptName).HasColumnName(@"DeptName").IsRequired().HasColumnType("nvarchar").HasMaxLength(50);
            Property(x => x.CourseCount).HasColumnName(@"CourseCount").IsOptional().HasColumnType("int");
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
